#!/usr/bin/env bash

set -eo pipefail
set -u

BRANCH="${CIRCLE_BRANCH:-$1}"

COMMIT_MSG=$(cat <<MSG
${2:-"auto-update"}

$(git status --short)
MSG
)

echo "$COMMIT_MSG" | git commit -F -
git push origin "$BRANCH"
