#!/usr/bin/env bash

set -eo pipefail
set -u

BRANCH="${CIRCLE_BRANCH:-$1}"

commit_msg() {
        cat <<MSG
$1

$(git status --short)
MSG
}

commit_msg ${2:-"auto-update"} | git commit -F -
git push origin "$BRANCH"
