#!/usr/bin/env bash

set -eo pipefail
set -u

# Config
BRANCH_DATE="$(date -u +%Y-%m-%d-%H-%M-%S)"
HUMAN_DATE="$(date -u '+%Y-%m-%d %H:%M:%S') UTC"
WORKING_BRANCH="dep-auto-update/${BRANCH_DATE}/${CIRCLE_BRANCH}"
git config hub.upstream "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
git config hub.oauthtoken "$DOMAINRBOT_TOKEN"

# Create new branch and PR
git add Gopkg.lock
git commit -m "dep auto-update"
git hub pull new -c "$WORKING_BRANCH" -b "$CIRCLE_BRANCH" -m "dep ensure -update @ ${HUMAN_DATE}

When \`dep\` can tell us what changed, we will add a summary here."
