#!/usr/bin/env bash

set -eo pipefail
set -u

pr_msg() {
        cat <<MSG
$1

$(git status --short)
MSG
}

# Config
BRANCH_DATE="$(date -u +%Y-%m-%d-%H-%M-%S)"
HUMAN_DATE="$(date -u '+%Y-%m-%d %H:%M:%S') UTC"
WORKING_BRANCH="auto-update/${BRANCH_DATE}/${CIRCLE_BRANCH}"
git config hub.upstream "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
git config hub.oauthtoken "$DOMAINRBOT_TOKEN"

# Create new branch and PR
git add --all .
git commit -m "$(echo "${1:-"auto-update"}")"
git hub pull new --create-branch "$WORKING_BRANCH" --base "$CIRCLE_BRANCH" -m "$(pr_msg "auto-update @ ${HUMAN_DATE}")"
