#!/usr/bin/env bash

set -eo pipefail

# Exit if outside git tree
[ -d .git ] ||
        git rev-parse --git-dir > /dev/null 2>&1 ||
        (echo "outside git work tree" && false)


(git diff-index --quiet HEAD -- && echo "nothing to do, working tree clean") || (
        ([[ "$#" -eq 0 ]] && echo "no command given") ||
        eval $(printf "%q " "$@")
)
